site_name: Hive Developers Site NICE!!
site_url: http://test-hivedevsite.withhive.com/

theme: 
  name: material
  language: ko
  custom_dir : template  
  
extra:
  version:
    provider: mike
  alternate:
    - name: Korean
      link: /ko/ 
      lang: ko
    - name: English
      link: /en/ 
      lang: en
    - name: Japanese
      link: /ja/
      lang: ja
    - name: Chinese
      link: /zh/
      lang: zh
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - SDK Guide:
    - 인증:
      - 로그인 로그아웃: dev/auth/login-helper.md
    - 프로모션:
      - 대배너: dev/promotion/fullbanners.md
  #   - FAQ: guide/faq.md
  #   - API Reference: guide/api-reference.md
  #   - Release Notes: guide/release-notes.md
  # - Tutorial:
  #   - Tutorial: tutorial/tutorial.md
  #   - Tutorial2: tutorial/tutorial2.md
  # - About:
  #   - About: about/about.md
  #   - About2: about/about2.md

# 바닐라 mkdocs 알아야할 정보들 정리 
# nav:
  # Note that a section cannot have a page assigned to it. Sections are only containers for child pages and sub-sections.
  # 가장 말단 경로(leaf node)만 링크를 걸 수 있음. 줄기 경로(branch node)는 링크를 걸 수 없으며, 섹션 이름만 표시됨.
  # 모든 페이지를 nav로 등록하는 것을 강력히 권장함.

# index.md가 홈페이지(랜딩페이지)가 됨.

# 문서 내 링크 사용 시 항상 상대 링크만 사용할 것. 절대 링크 사용 시 로컬에서는 정상이더라도, 배포 시 문제가 생길 수 있음.
  # 확장 마크다운 문법에서 toc extensions을 사용해야 네임드 앵커를 사용 가능. https://python-markdown.github.io/extensions/toc/

# toc extensions으로 permalink 사용 가능: https://www.mkdocs.org/user-guide/writing-your-docs/#linking-to-pages

# 바닐라 마크다운 문법을 먼저 알고, 그 다음에 파이선 마크다운 문법을 배워야함. 더 나아가, 확장 마크다운 문법도 지원함. 단, 큰 차이는 없음.
# 마크다운 문법: https://www.markdownguide.org/basic-syntax/
# 파이선 마크다운 문법: https://python-markdown.github.io/#differences
# 확장 마크다운 문법: https://www.mkdocs.org/user-guide/configuration/#markdown_extensions

# MkDocs는 HTML 포맷도 지원하긴 한다. 다만, MkDocs는 raw HTML에 포함된 링크를 확인하거나 변환할 수 없습니다. raw HTML 내에 내부 링크를 포함하는 경우 렌더링한 문서(빌드한 HTML 문서)에 맞게 링크 형식을 수동으로 지정해야 합니다.

# https://www.mkdocs.org/user-guide/writing-your-docs/#meta-data 전까지 읽었음.

# mkdocs가 title 결정하는 우선 순위: nav가 1순위임
# A title defined in the nav configuration setting for a document.
# A title defined in the title meta-data key of a document.
# A level 1 Markdown header on the first line of the document body.
# (Setext-style headers are supported only since MkDocs 1.5.)
# The filename of a document.

# The first blank line ends all meta-data for the document. Therefore, the first line of a document must not be blank.
# MultiMarkdownStyle 메타 데이터를 쓰려면 빈 공백을 조심해야 함. 빈 공백 라인이 있으면, 그 다음 라인부터는 메타 데이터로 인식하지 않음.

# 바닐라 mkdocs 알아야할 정보들 정리  ------------------------------ 끝
